[package]
name = "notes-api"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.45.1", features = ["full"] }
axum = "0.8.4"
colored = "3.0.0"
serde = { version = "1.0.219", features = ["derive"] }
